export const menusNotifications = [
  { code: 'dash', notifications: false },
  { code: 'bu', notifications: true },
  { code: 'snap', notifications: false },
  { code: 'api', notifications: true },
  { code: 'log', notifications: false },
  { code: 'dbug', notifications: true },
]

export const businessUnits = [
  {
    id: 1,
    name: 'Exchange',
    slug: 'exchange',
    code: 'EXCG',
    accountCount: "35",
    currencyCount: "6",
    balance: "16463613.68740567",
    gap: "1833.61636341",
    description: 'Concerns the assets associated with CAMP Investment Exchange, including Swap and Spot Market products. Assets include customer funds, working capital, and escrow funds.',
    alerts: ["gap_unacceptable_entireBU", "gap_critical_currency", "api_request_failed"],
    snapshotSettings: {
      startingDate: "2024-05-20T11:23Z",
      intervalType: "hour",
      intervalOption: "time-same-time-every-day",
      primaryInterval: 2,
      secondaryInterval: 30,
      weekArray: undefined,
    },
    discrAlertConf: {
      buSendPush: true,
      buSendEmail: false,
      curSendPush: true,
      curSendEmail: false,
      repeatNotif: false,
      basis: "usd",
      critHigh: 12000,
      acctbleHigh: 5000,
      acctbleLow: -5000,
      critLow: -12000,
    }
  },
  {
    id: 2,
    name: 'Fixed Deposit',
    slug: 'fixed-deposit',
    code: 'FXDT',
    accountCount: "30",
    currencyCount: "8",
    balance: "13692766.98141219",
    gap: "905.71103009",
    description: 'Concerns the assets in custody of product providers in order to provide CAMP Investment customers with returns from our Fixed Deposit product.',
    alerts:null,
    snapshotSettings: {
      startingDate: "2024-05-20T11:23Z",
      intervalType: "hour",
      intervalOption: "time-same-time-every-day",
      primaryInterval: 4,
      secondaryInterval: 0,
      weekArray: undefined,
    },
    discrAlertConf: {
      buSendPush: true,
      buSendEmail: true,
      curSendPush: true,
      curSendEmail: true,
      repeatNotif: false,
      basis: "percent",
      critHigh: null,
      acctbleHigh: null,
      acctbleLow: -2,
      critLow: -5,
    }
  },
  { id: 3,
    name: 'Staking',
    slug: 'staking',
    code: 'STKG',
    accountCount: "11",
    currencyCount: "5",
    balance: "13577524.32265859",
    gap: "4226.6919247",
    description: 'Concerns the assets required to maintain the Staking products, whether derived from user staking or internal staking. Assets are stored in staking wallets or external staking providers',
    alerts: ["too_long_since_last_update"],
    snapshotSettings: null,
    discrAlertConf: null
  },
  { id: 4,
    name:'Market Maker Bot',
    slug: 'market-maker-bot',
    code: 'MMBT', accountCount: "52",
    currencyCount: "19",
    balance: "83694865.57046921", 
    gap: "3124.88460947",
    description: 'Concerns the assets in multiple counterparties in order to arbitrage the discrepancies between their order books.',
    alerts: ["gap_unacceptable_entireBU", "blockchain_connection_failed"],
    snapshotSettings: {
      startingDate: "2024-05-20T11:23Z",
      intervalType: "week",
      intervalOption: undefined,
      primaryInterval: 1,
      secondaryInterval: 0,
      weekArray: [true, false, false, false, true, false, false],
    },
    discrAlertConf: {
      buSendPush: false,
      buSendEmail: true,
      curSendPush: false,
      curSendEmail: false,
      repeatNotif: true,
      basis: "usd",
      critHigh: null,
      acctbleHigh: 5000,
      acctbleLow: -3000,
      critLow: -8000,
    }
  },
  {
    id: 5, 
    name: 'Loan',
    slug: 'loan',
    code: 'LOAN',
    accountCount: "23",
    currencyCount: "8",
    balance: "67659470.58309516",
    gap: "794.59775464",
    description: 'Concerns the assets used in Loan, product that offers liquid fiat and stablecoins loaned with comparatively volatile crypto assets.',
    alerts: ["api_config_error"],
    snapshotSettings: null,
    discrAlertConf: null
  },
]

export const defaultSnapshotSettings = {
  startingDate: "2024-01-01T11:23Z",
  intervalType: "hour",
  intervalOption: "time-same-time-every-day",
  primaryInterval: 12,
  secondaryInterval: 0,
  weekArray: undefined
}
